language: swift
osx_image: xcode11.2
xcode_workspace: TMDB.xcworkspace
xcode_sdk: iphonesimulator13.2
env:
 - DESTINATION="platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2.2" SCHEME="TMDB"

branches:
  only:
  - master
  - /^release-.*$/

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/TMDB-*/
- rvm use $RVM_RUBY_VERSION
- brew update
- brew upgrade swiftlint
- pod repo update


script:
- xcodebuild -workspace TMDB.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" clean test | xcpretty