language: swift
osx_image: xcode11.6
xcode_workspace: TMDB.xcworkspace
xcode_sdk: iphonesimulator13.6
env:
 - DESTINATION="platform=iOS Simulator,name=iPhone 11,OS=13.6" SCHEME="TMDB"

branches:
  only:
  - master
  - /^release-.*$/

before_install:
- pod install

script:
- xcodebuild -workspace TMDB.xcworkspace -scheme "$SCHEME" -derivedDataPath BUILDPATH -destination "$DESTINATION" -enableCodeCoverage YES clean build test