language: swift
osx_image: xcode11.2
xcode_workspace: TMDB.xcworkspace
xcode_sdk: iphonesimulator13.

branches:
  only:
  - master
  - /^release-.*$/

before_install:
- pod install

script:
- xcodebuild -workspace TMDB.xcworkspace -scheme TMDB -sdk iphonesimulator13.2 -configuration Debug build test