language: swift
osx_image: xcode11.6
xcode_workspace: TMDB.xcworkspace
xcode_sdk: iphonesimulator13.2
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

branches:
  only:
  - master
  - /^release-.*$/

before_install:
- pod install

script:
- xcodebuild -workspace TMDB.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" clean test | xcpretty